#ifndef _BP1048_APP_H
#define _BP1048_APP_H
#include "bp1048_bsp.h"
typedef struct _stBp1048FunctionEvent_t
{
	BOOL	bAllAudioOutputChangeFlag;
	u8		u8AllAudioOutput;
	BOOL	bSensitivityChangeFlag[Def_inport_num];
	u8		u8Sensitivity[Def_inport_num][3];
	BOOL	bInputGainChangeFlag[Def_inport_num];
	u8		u8InputGain[Def_inport_num][3];
	BOOL	bInputMuteChangeFlag[Def_inport_num];
	u8		u8InputMute[Def_inport_num][3];
	BOOL	bReversePhaseChangeFlag[Def_inport_num];
	u8		u8ReversePhase[Def_inport_num][3];
	BOOL	bTestSignalCtrlChangeFlag[Def_inport_num];
	u8		u8TestSignalCtrl[Def_inport_num][3];
	BOOL	bTestSignalFreqChangeFlag[Def_inport_num];
	u8		u8TestSignalFreq[Def_inport_num][3];
	BOOL	bTestSignalLevelChangeFlag[Def_inport_num];
	u8		u8TestSignalLevel[Def_inport_num][3];
	BOOL	bCompressorCtrlChangeFlag[Def_inport_num];
	u8		u8CompressorCtrl[Def_inport_num][3];
	BOOL	bCompressorGainChangeFlag[Def_inport_num];
	u8		u8CompressorGain[Def_inport_num][3];
	BOOL	bCompressorThresholdChangeFlag[Def_inport_num];
	u8		u8CompressorThreshold[Def_inport_num][3];
	BOOL	bCompressorRatioChangeFlag[Def_inport_num];
	u8		u8CompressorRatio[Def_inport_num][3];
	BOOL	bCompressorStartTimeChangeFlag[Def_inport_num];
	u8		u8CompressorStartTime[Def_inport_num][3];
	BOOL	bCompressorReleaseTimeChangeFlag[Def_inport_num];
	u8		u8CompressorReleaseTime[Def_inport_num][3];
	BOOL	bAutoGainCtrlChangeFlag[Def_inport_num];
	u8		u8AutoGainCtrl[Def_inport_num][3];
	BOOL	bAutoGainThresholdChangeFlag[Def_inport_num];
	u8		u8AutoGainThreshold[Def_inport_num][3];
	BOOL	bAutoGainTargetThresholdChangeFlag[Def_inport_num];
	u8		u8AutoGainTargetThreshold[Def_inport_num][3];
	BOOL	bAutoGainStartTimeChangeFlag[Def_inport_num];
	u8		u8AutoGainStartTime[Def_inport_num][3];
	BOOL	bAutoGainReleaseTimeChangeFlag[Def_inport_num];
	u8		u8AutoGainReleaseTime[Def_inport_num][3];
	BOOL	bEQTypeChangeFlag[Def_inport_num];
	u8		u8EQType[Def_inport_num][3];
	BOOL	bEQGainChangeFlag[Def_inport_num];
	u8		u8EQGain[Def_inport_num][3];
	BOOL	bEQQualityFactorChangeFlag[Def_inport_num];
	u8		u8EQQualityFactor[Def_inport_num][3];
	BOOL	bEQCtrlChangeFlag[Def_inport_num];
	u8		u8EQCtrl[Def_inport_num][3];
	BOOL	bHowlingSuppressorCtrlChangeFlag[Def_inport_num];
	u8		u8HowlingSuppressorCtrl[Def_inport_num][3];
	BOOL	bHowlingSuppressorGradeChangeFlag[Def_inport_num];
	u8		u8HowlingSuppressorGrade[Def_inport_num][3];
	BOOL	bHowlingSuppressorFreqShiftChangeFlag[Def_inport_num];
	u8		u8HowlingSuppressorFreqShift[Def_inport_num][3];
	BOOL	bNoiseSuppressorGradeChangeFlag[Def_inport_num];
	u8		u8NoiseSuppressorGrade[Def_inport_num][3];
	BOOL	bNoiseSuppressorThresholdChangeFlag[Def_inport_num];
	u8		u8NoiseSuppressorThreshold[Def_inport_num][3];
	BOOL	bNoiseSuppressorRatioChangeFlag[Def_inport_num];
	u8		u8NoiseSuppressorRatio[Def_inport_num][3];
	BOOL	bNoiseSuppressorStartTimeChangeFlag[Def_inport_num];
	u8		u8NoiseSuppressorStartTime[Def_inport_num][3];
	BOOL	bNoiseSuppressorReleaseTimeChangeFlag[Def_inport_num];
	u8		u8NoiseSuppressorReleaseTime[Def_inport_num][3];
	BOOL	bNoiseSuppressorCtrlChangeFlag[Def_inport_num];
	u8		u8NoiseSuppressorCtrl[Def_inport_num][3];
	BOOL	bEchoCanceller_CtrlChangeFlag[Def_inport_num];
	u8		u8EchoCancellerCtrl[Def_inport_num][3];
	BOOL	bEchoCancellerGradeChangeFlag[Def_inport_num];
	u8		u8EchoCancellerGrade[Def_inport_num][3];
	BOOL	bExciterCtrlChangeFlag[Def_inport_num];
	u8		u8ExciterCtrl[Def_inport_num][3];
	BOOL	bHfreqExciterGradeChangeFlag[Def_inport_num];
	u8		u8HfreqExciterGrade[Def_inport_num][3];
	BOOL	bLfreqExciterGradeChangeFlag[Def_inport_num];
	u8		u8LfreqExciterGrade[Def_inport_num][3];
	BOOL	bCallInputChangeFlag[Def_inport_num];
	u8		u8CallInput[Def_inport_num][3];
	BOOL	bBackgroundInputChangeFlag[Def_inport_num];
	u8		u8BackgroundInput[Def_inport_num][3];
	BOOL	bDuckingGainChangeFlag[Def_inport_num];
	u8		u8DuckingGain[Def_inport_num][3];
	BOOL	bDuckingThresholdChangeFlag[Def_inport_num];
	u8		u8DuckingThreshold[Def_inport_num][3];
	BOOL	bDuckingDepthChangeFlag[Def_inport_num];
	u8		u8DuckingDepth[Def_inport_num][3];
	BOOL	bDuckingStartTimeChangeFlag[Def_inport_num];
	u8		u8DuckingStartTime[Def_inport_num][3];
	BOOL	bDuckingHoldTimeChangeFlag[Def_inport_num];
	u8		u8DuckingHoldTime[Def_inport_num][3];
	BOOL	bDuckingReleaseTimeChangeFlag[Def_inport_num];
	u8		u8DuckingReleaseTime[Def_inport_num][3];
	BOOL	bDuckingCtrlChangeFlag[Def_inport_num];
	u8		u8DuckingCtrl[Def_inport_num][3];
	BOOL	bMatrixSwitchingChangeFlag[Def_inport_num];
	u8		u8MatrixSwitching[Def_inport_num][3];
	BOOL	bOutputDelayTimeChangeFlag[Def_inport_num];
	u8		u8OutputDelayTime[Def_inport_num][3];
	BOOL	bOutputDelayCtrlChangeFlag[Def_inport_num];
	u8		u8OutputDelayCtrl[Def_inport_num][3];
	BOOL	bUSBplayerCtrlChangeFlag[Def_inport_num];
	u8		u8USBplayerCtrl[Def_inport_num][3];

}stBp1048FunctionEvent_t;

u8 app_All_AudioOutput_Ctrl(u8 u8Dev,u8 *command);
u8 app_Input_Sensitivity(u8 u8Dev,u8 *command);
u8 app_Input_Gain(u8 u8Dev,u8 *command);
u8 app_Input_Mute(u8 u8Dev,u8 *command);
u8 app_Input_Reverse_phase(u8 u8Dev,u8 *command);
u8 app_Input_TestSignal_Ctrl(u8 u8Dev,u8 *command);
u8 app_Input_TestSignal_Freq(u8 u8Dev,u8 *command);
u8 app_Input_TestSignal_Level(u8 u8Dev,u8 *command);
u8 app_Input_Compressor_Ctrl(u8 u8Dev,u8 *command);
u8 app_Input_Compressor_Gain(u8 u8Dev,u8 *command);
u8 app_Input_Compressor_Threshold(u8 u8Dev,u8 *command);
u8 app_Input_Compressor_Ratio(u8 u8Dev,u8 *command);
u8 app_Input_Compressor_StartTime(u8 u8Dev,u8 *command);
u8 app_Input_Compressor_ReleaseTime(u8 u8Dev,u8 *command);
u8 app_Input_AutoGain_Ctrl(u8 u8Dev,u8 *command);
u8 app_Input_AutoGain_Threshold(u8 u8Dev,u8 *command);
u8 app_Input_AutoGain_TargetThreshold(u8 u8Dev,u8 *command);
u8 app_Input_AutoGain_Ratio(u8 u8Dev,u8 *command);
u8 app_Input_AutoGain_StartTime(u8 u8Dev,u8 *command);
u8 app_Input_AutoGain_ReleaseTime(u8 u8Dev,u8 *command);
u8 app_Input_EQ_Type(u8 u8Dev,u8 *command);
u8 app_Input_EQ_Gain(u8 u8Dev,u8 *command);
u8 app_Input_EQ_QualityFactor(u8 u8Dev,u8 *command);
u8 app_Input_EQ_Ctrl(u8 u8Dev,u8 *command);
u8 app_Input_HowlingSuppressor_Ctrl(u8 u8Dev,u8 *command);
u8 app_Input_HowlingSuppressor_Grade(u8 u8Dev,u8 *command);
u8 app_Input_HowlingSuppressor_FreqShift(u8 u8Dev,u8 *command);
u8 app_Input_NoiseSuppressor_Grade(u8 u8Dev,u8 *command);
u8 app_Input_NoiseSuppressor_Threshold(u8 u8Dev,u8 *command);
u8 app_Input_NoiseSuppressor_Ratio(u8 u8Dev,u8 *command);
u8 app_Input_NoiseSuppressor_StartTime(u8 u8Dev,u8 *command);
u8 app_Input_NoiseSuppressor_ReleaseTime(u8 u8Dev,u8 *command);
u8 app_Input_NoiseSuppressor_Ctrl(u8 u8Dev,u8 *command);
u8 app_Input_EchoCanceller_Ctrl(u8 u8Dev,u8 *command);
u8 app_Input_EchoCanceller_Grade(u8 u8Dev,u8 *command);
u8 app_Input_Exciter_Ctrl(u8 u8Dev,u8 *command);
u8 app_Input_HfreqExciter_Grade(u8 u8Dev,u8 *command);
u8 app_Input_LfreqExciter_Grade(u8 u8Dev,u8 *command);
u8 app_Input_CallInput(u8 u8Dev,u8 *command);
u8 app_Input_BackgroundInput(u8 u8Dev,u8 *command);
u8 app_Input_Ducking_Gain(u8 u8Dev,u8 *command);
u8 app_Input_Ducking_Threshold(u8 u8Dev,u8 *command);
u8 app_Input_Ducking_Depth(u8 u8Dev,u8 *command);
u8 app_Input_Ducking_StartTime(u8 u8Dev,u8 *command);
u8 app_Input_Ducking_HoldTime(u8 u8Dev,u8 *command);
u8 app_Input_Ducking_ReleaseTime(u8 u8Dev,u8 *command);
u8 app_Input_Ducking_Ctrl(u8 u8Dev,u8 *command);
u8 app_MatrixSwitching(u8 u8Dev,u8 *command);
u8 app_Output_DelayTime(u8 u8Dev,u8 *command);
u8 app_Output_Delay_Ctrl(u8 u8Dev,u8 *command);
u8 app_USBplayer_Ctrl(u8 u8Dev,u8 *command);
void app_BP1048_process(u8 dev);

#endif

